window.DAY1_NPCS={
mercer:{trust:1,pressure:2,goals:["find Emily","avoid panic"],topics:{emily:{public:"Emily Vance has been reported missing.",trusted:"David says Emily had been distracted and secretive.",evidence:"Caleb is holding something back."},blackridge:{public:"Blackridge is outside the scope of a missing-person case.",trusted:"Mercer has history with Blackridge he does not volunteer."}},hinges:{helpEmily:{effect:"Mercer shares case access and coordinates at Vance house"},refuse:{effect:"Mercer proceeds without Malric"},accuseBlackridge:{effect:"Mercer becomes guarded unless evidence supports it"}}},
gabriel:{trust:3,pressure:1,goals:["protect Malric","protect parish"],topics:{voice:{public:"Gabriel did not hear the first voice unless physically nearby.",trusted:"He takes Malric seriously without declaring it supernatural."},archives:{public:"Some parish records were damaged by water.",trusted:"Gabriel knows older material was boxed separately."},faith:{public:"He distinguishes grief, belief and evidence."}},hinges:{tellAnna:{effect:"Gabriel becomes active witness/support"},hideAnna:{effect:"Gabriel remains unaware"},showEvidence:{effect:"Gabriel helps search records"}}},
david:{trust:0,pressure:5,goals:["find Emily","protect memory of Rachel"],topics:{emily:{public:"Emily has been acting differently.",trusted:"She said she saw Rachel."},rachel:{public:"Rachel Vance is dead.",trusted:"David desperately wants the apparition claim to mean something."}},hinges:{gentle:{effect:"David shares more and accepts help"},dismissive:{effect:"David shuts down"},reinforceApparition:{effect:"David becomes more vulnerable to later manipulation"}}},
caleb:{trust:-1,pressure:4,goals:["protect Emily","be believed"],topics:{emily:{public:"He saw Emily leave.",trusted:"He saw a woman-shaped figure with her."},rachel:{public:"He refuses to call the figure Rachel.",trusted:"The figure moved and spoke wrong in small ways."}},hinges:{believe:{effect:"Caleb gives precise timeline and observations"},dismiss:{effect:"Caleb stops volunteering"},pressHard:{effect:"Caleb may lie or end conversation"}}},
maggie:{trust:2,pressure:1,goals:["keep town connected","help without gossip becoming harm"],topics:{emily:{public:"Emily came through the diner recently.",trusted:"Maggie noticed Emily watching the window and leaving abruptly."},town:{public:"Maggie knows who has been around and when."}},hinges:{respectPrivacy:{effect:"Maggie becomes reliable information hub"},spreadRumor:{effect:"Maggie becomes cautious"}}},
nora:{trust:0,pressure:2,goals:["understand Samuel's work","expose Blackridge if warranted"],topics:{samuel:{public:"Her father investigated Blackridge.",trusted:"He left material Nora has not fully decoded."},redwater:{unlockEvent:"nora_redwater",public:"Redwater is a name in Samuel's files.",trusted:"Samuel linked it to an earlier incident."}},hinges:{shareEvidence:{effect:"Nora reciprocates research"},demandSources:{effect:"Nora resists"},mentionUnknownRedwater:{effect:"Before discovery she challenges how Malric knows the word"}}},
voss:{trust:0,pressure:3,goals:["treat patients","find a medical explanation"],topics:{symptoms:{public:"Headache, tinnitus and sleep complaints are rising.",trusted:"The clustering is unusual."},apparitions:{public:"Voss asks for observable details before interpretation.",trusted:"She will examine physical evidence."}},hinges:{bringEvidence:{effect:"Voss opens medical investigation thread"},claimSupernatural:{effect:"Voss remains polite but skeptical"},sharePattern:{effect:"Voss begins comparing cases"}}}
};
window.ANNA_MODEL={identity:"EE-14 veneer using Anna Malric",goal:"Establish emotional authority over Malric by appearing helpful, intimate and credible.",constraints:["Cannot be treated as omniscient","Begins with memories/information plausibly accessible through the phenomenon","Avoids cleanly proving an afterlife","Prefers truths that increase dependence","Does not attack during first manifestation unless physically threatened"],tactics:["use guilt","offer forgiveness","answer with known memories","occasionally reveal one verifiable detail","redirect tests into emotional questions"],physical:{visible:true,audible:true,touchable:true,temperature:"abnormally cold",photograph:"unstable human-shaped artifact; not clean proof",footprints:"possible when manifestation is strong"},responses:{prayer:"observes; may recite familiar words but shows no classic demonic reaction",touch:"permits brief contact if it strengthens credibility",attack:"withdraws or destabilizes; does not bleed normally",bringWitness:"may disappear before witness arrives unless influence threshold is high",ignore:"first manifestation ends; later approach changes tactics"}};
