window.Game=(function(){
function fresh(){return{day:-1,min:1122,loc:"St. Bartholomew's",story:8,invest:4,explore:12,condition:"Healthy",fatigue:"Rested",crisis:"UNEASY",knowledge:Engine03.initialKnowledge(),journal:["6:42 PM — Evening at St. Bartholomew's begins."],cases:["Emily Vance","The Visitations"],inventory:["Phone","Keys","Wallet","Flashlight","Pocketknife","Rosary","Notebook","Lighter"],scene:{mode:"FREE_ACTION",npc:null,subject:"opening choice",pendingRoll:null},opening:{mercerCall:true,annaVoice:true,annaEncountered:false},flags:{mercerFavor:false,annaContact:false,aqua:false},conversation:{anna:{turns:0,accused:false,askedDeath:false,trust:0}},npcMemory:{},relationships:{mercer:1,gabriel:3,david:0,caleb:-1,maggie:2,nora:0,voss:0},evidence:[],resolvedEvents:[],activeEvents:[],perceivedEvents:[],npcs:{gabriel:{loc:"St. Bartholomew's"},mercer:{loc:"Sheriff's Office"},david:{loc:"Vance Residence"},caleb:{loc:"Vance Residence"},maggie:{loc:"Maggie's Diner"},nora:{loc:"Gazette"},voss:{loc:"Clinic"},anna:{present:false,loc:null}}}}
let S=fresh();
function migrate(){if(!S.knowledge)S.knowledge=Engine03.initialKnowledge();if(!S.scene)S.scene={mode:"FREE_ACTION",npc:null,subject:null,pendingRoll:null};if(!S.opening)S.opening={mercerCall:true,annaVoice:true,annaEncountered:false};if(!S.conversation)S.conversation={anna:{turns:0,accused:false,askedDeath:false,trust:0}};if(!S.resolvedEvents)S.resolvedEvents=[];if(!S.npcMemory)S.npcMemory={};if(!S.relationships)S.relationships={mercer:1,gabriel:3,david:0,caleb:-1,maggie:2,nora:0,voss:0};if(!S.evidence)S.evidence=[];if(!S.perceivedEvents)S.perceivedEvents=[];if(!S.npcs)S.npcs=fresh().npcs}
function syncWorld(){if(!window.Day1Sim)return;Day1Sim.sync(S)}
function processEvents(before,after){if(!window.WORLD||!WORLD.events)return[];let perceived=[];for(let e of WORLD.events){if(e.at>before&&e.at<=after&&!S.resolvedEvents.includes(e.id)){S.resolvedEvents.push(e.id);if(!e.location||e.location===S.loc){if(e.location===S.loc){perceived.push(e);S.perceivedEvents.push(e.id)}}}}return perceived}
function save(){syncWorld();localStorage.setItem("sbs03",JSON.stringify(S))}
function load(){let x=localStorage.getItem("sbs03");if(x)S=JSON.parse(x);migrate();syncWorld();return S}
function reset(){S=fresh();save();location.reload()}
function time(){let h=Math.floor(S.min/60)%24,m=S.min%60;return(h%12||12)+":"+String(m).padStart(2,"0")+" "+(h>=12?"PM":"AM")}
function preflight(action){syncWorld();let meta=Engine03.metaknowledge(action,S.knowledge);return{metaknowledge:meta,location:S.loc,scene:S.scene,knownLocations:Object.keys(S.knowledge.locations||{}),peopleHere:window.Day1Sim?Day1Sim.visiblePeople(S):[],minute:S.min,dueHere:window.Day1Sim?Day1Sim.eventSummary(S).map(e=>e.id):[],relationships:S.relationships,npcMemory:S.npcMemory,evidence:S.evidence,locationContent:window.DAY1_CONTENT&&DAY1_CONTENT.locations[S.loc]?DAY1_CONTENT.locations[S.loc]:null}}
function apply(o,action){o=Engine03.invariant(o);let before=S.min,mins=Number(o.minutes||0);S.min+=mins;if(S.min>=1440){S.min=1440;S.flags.day1Complete=true}if(o.location&&o.location!==S.loc){if(!Engine03.knows(S.knowledge,o.location)&&!o.locationDiscovered)throw new Error("ENGINE_INVARIANT_UNKNOWN_LOCATION");S.loc=o.location}
if(o.locationDiscovered)Engine03.discover(S.knowledge,o.locationDiscovered,"DISCOVERED");if(o.routeDiscovered){let p=o.routeDiscovered.split(" → ");if(p.length===2)Engine03.discoverRoute(S.knowledge,p[0],p[1],"DISCOVERED")}
S.story=Math.min(100,S.story+Number(o.storyDelta||0));S.invest=Math.min(100,S.invest+Number(o.investigationDelta||0));S.explore=Math.min(100,S.explore+Number(o.explorationDelta||0));(o.factsLearned||[]).forEach(f=>{if(!S.knowledge.facts.includes(f))S.knowledge.facts.push(f)});(o.discoveries||[]).forEach(d=>{if(d==="Aqua Heresis"&&!S.cases.includes(d)){S.cases.push(d);S.flags.aqua=true}if(d.includes("Mercer"))S.flags.mercerFavor=true});
if(o.memoryPatch){for(let id in o.memoryPatch){S.npcMemory[id]=S.npcMemory[id]||[];for(let m of o.memoryPatch[id])if(!S.npcMemory[id].includes(m))S.npcMemory[id].push(m)}}if(o.relationshipPatch){for(let id in o.relationshipPatch)S.relationships[id]=(S.relationships[id]||0)+Number(o.relationshipPatch[id])}if(o.evidenceAdded){for(let e of o.evidenceAdded)if(!S.evidence.includes(e))S.evidence.push(e)}if(o.scene)S.scene=o.scene;if(o.statePatch){if(o.statePatch.openingChoice==="mercer"){S.opening.mercerCall=false;S.opening.annaVoice=true}if(o.statePatch.openingChoice==="anna"){S.opening.annaVoice=false}if(o.statePatch.annaEncountered){S.opening.annaEncountered=true;S.npcs.anna=S.npcs.anna||{};S.npcs.anna.present=true;S.npcs.anna.loc=S.loc}if(o.statePatch.annaWithdrawn){S.npcs.anna=S.npcs.anna||{};S.npcs.anna.present=false;S.npcs.anna.loc=null;}if(o.statePatch.annaAccused)S.conversation.anna.accused=true;if(o.statePatch.annaAskedDeath)S.conversation.anna.askedDeath=true}
syncWorld();let events=processEvents(before,S.min);if(S.scene&&S.scene.npc==="anna")S.conversation.anna.turns++;S.journal.push(time()+" — "+(o.journal||action));for(let e of events)S.journal.push(time()+" — "+e.summary);save();o.perceivedEvents=events;return o}
async function resolve(action){let pf=preflight(action),r=await fetch("/api/resolve",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,state:S,world:window.WORLD,preflight:pf})});let o=await r.json();if(!r.ok)throw new Error(o.error||"Resolver unavailable");return Engine03.invariant(o)}
return{state:()=>S,load,save,reset,time,apply,resolve,preflight,fresh,syncWorld}})();