window.Game=(function(){
function fresh(){return{day:-1,min:1122,loc:"St. Bartholomew's",story:8,invest:4,explore:12,condition:"Healthy",fatigue:"Rested",crisis:"UNEASY",knowledge:Engine03.initialKnowledge(),journal:["6:42 PM — Evening at St. Bartholomew's begins."],cases:["Emily Vance","The Visitations"],inventory:["Phone","Keys","Wallet","Flashlight","Pocketknife","Rosary","Notebook","Lighter"],scene:{mode:"FREE_ACTION",npc:null,subject:"opening choice",pendingRoll:null},opening:{mercerCall:true,annaVoice:true,annaEncountered:false},flags:{mercerFavor:false,annaContact:false,aqua:false},conversation:{anna:{turns:0,accused:false,askedDeath:false,trust:0}},npcs:{gabriel:{loc:"St. Bartholomew's"},mercer:{loc:"Sheriff's Office"},anna:{present:false,loc:null}}}}
let S=fresh();
function migrate(){if(!S.knowledge)S.knowledge=Engine03.initialKnowledge();if(!S.scene)S.scene={mode:"FREE_ACTION",npc:null,subject:null,pendingRoll:null};if(!S.opening)S.opening={mercerCall:true,annaVoice:true,annaEncountered:false};if(!S.conversation)S.conversation={anna:{turns:0,accused:false,askedDeath:false,trust:0}}}
function save(){localStorage.setItem("sbs03",JSON.stringify(S))}
function load(){let x=localStorage.getItem("sbs03");if(x)S=JSON.parse(x);migrate();return S}
function reset(){S=fresh();save();location.reload()}
function time(){let h=Math.floor(S.min/60)%24,m=S.min%60;return(h%12||12)+":"+String(m).padStart(2,"0")+" "+(h>=12?"PM":"AM")}
function preflight(action){let meta=Engine03.metaknowledge(action,S.knowledge);return{metaknowledge:meta,location:S.loc,scene:S.scene,knownLocations:Object.keys(S.knowledge.locations||{})}}
function apply(o,action){o=Engine03.invariant(o);S.min+=Number(o.minutes||0);if(o.location&&o.location!==S.loc){if(!Engine03.knows(S.knowledge,o.location)&&!o.locationDiscovered)throw new Error("ENGINE_INVARIANT_UNKNOWN_LOCATION");S.loc=o.location}
S.story=Math.min(100,S.story+Number(o.storyDelta||0));S.invest=Math.min(100,S.invest+Number(o.investigationDelta||0));S.explore=Math.min(100,S.explore+Number(o.explorationDelta||0));
if(o.locationDiscovered)Engine03.discover(S.knowledge,o.locationDiscovered,"DISCOVERED");if(o.routeDiscovered){let p=o.routeDiscovered.split(" → ");if(p.length===2)Engine03.discoverRoute(S.knowledge,p[0],p[1],"DISCOVERED")}
(o.factsLearned||[]).forEach(f=>{if(!S.knowledge.facts.includes(f))S.knowledge.facts.push(f)});(o.discoveries||[]).forEach(d=>{if(d==="Aqua Heresis"&&!S.cases.includes(d)){S.cases.push(d);S.flags.aqua=true}if(d.includes("Mercer"))S.flags.mercerFavor=true});
if(o.scene)S.scene=o.scene;if(o.statePatch){if(o.statePatch.openingChoice==="mercer"){S.opening.mercerCall=false;S.opening.annaVoice=true}if(o.statePatch.openingChoice==="anna"){S.opening.annaVoice=false;S.opening.annaEncountered=true}if(o.statePatch.annaAccused)S.conversation.anna.accused=true;if(o.statePatch.annaAskedDeath)S.conversation.anna.askedDeath=true}
if(S.scene&&S.scene.npc==="anna")S.conversation.anna.turns++;S.journal.push(time()+" — "+(o.journal||action));save();return o}
async function resolve(action){let pf=preflight(action),r=await fetch("/api/resolve",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,state:S,world:window.WORLD,preflight:pf})});let o=await r.json();if(!r.ok)throw new Error(o.error||"Resolver unavailable");return Engine03.invariant(o)}
return{state:()=>S,load,save,reset,time,apply,resolve,preflight,fresh}})();