window.WORLD={
meta:{version:"0.5",slice:"Malric Day -1",startMinute:1122,endMinute:1440},
locations:{
"St. Bartholomew's":{id:"church",name:"St. Bartholomew's Church",exits:["Rectory","Cemetery","Downtown"],discoverable:["Church Basement"],travel:{Rectory:1,Cemetery:2,Downtown:12}},
"Rectory":{id:"rectory",name:"Rectory",exits:["St. Bartholomew's","Downtown"],travel:{"St. Bartholomew's":1,Downtown:12}},
"Church Basement":{id:"basement",name:"Church Basement",exits:["St. Bartholomew's"],discoverable:["Archive Room"],travel:{"St. Bartholomew's":1}},
"Archive Room":{id:"archive",name:"Parish Archive",exits:["Church Basement"],travel:{"Church Basement":0}},
"Cemetery":{id:"cemetery",name:"St. Bartholomew's Cemetery",exits:["St. Bartholomew's"],travel:{"St. Bartholomew's":2}},
"Downtown":{id:"downtown",name:"Downtown Whispering Falls",exits:["St. Bartholomew's","Sheriff's Office","Maggie's Diner","Gazette","Clinic","Vance Residence","Reservoir"],travel:{"St. Bartholomew's":12,"Sheriff's Office":3,"Maggie's Diner":2,Gazette:3,Clinic:7,"Vance Residence":9,Reservoir:18}},
"Sheriff's Office":{id:"sheriff",name:"Sheriff's Office",exits:["Downtown"],travel:{Downtown:3}},
"Maggie's Diner":{id:"maggies",name:"Maggie's Diner",exits:["Downtown"],travel:{Downtown:2}},
"Gazette":{id:"gazette",name:"Bellweather County Gazette",exits:["Downtown"],travel:{Downtown:3}},
"Clinic":{id:"clinic",name:"Bellweather Clinic",exits:["Downtown"],travel:{Downtown:7}},
"Vance Residence":{id:"vance",name:"Vance Residence",exits:["Downtown"],travel:{Downtown:9}},
"Reservoir":{id:"reservoir",name:"Whispering Reservoir",exits:["Downtown"],travel:{Downtown:18}}},
characters:{malric:{knownLocations:["St. Bartholomew's","Rectory","Cemetery","Downtown","Sheriff's Office","Maggie's Diner","Gazette","Clinic","Vance Residence","Reservoir"],knownFacts:["Emily Vance is missing","Malric knows the public layout of Whispering Falls"]}},
npcs:{
gabriel:{name:"Father Gabriel Reed",schedule:[[1122,1200,"St. Bartholomew's"],[1200,1320,"Rectory"],[1320,1440,"St. Bartholomew's"]]},
mercer:{name:"Sheriff Thomas Mercer",schedule:[[1122,1150,"Sheriff's Office"],[1150,1250,"Vance Residence"],[1250,1440,"Sheriff's Office"]]},
david:{name:"David Vance",schedule:[[1122,1440,"Vance Residence"]]},
caleb:{name:"Caleb Vance",schedule:[[1122,1440,"Vance Residence"]]},
maggie:{name:"Maggie Donnelly",schedule:[[1122,1320,"Maggie's Diner"]]},
nora:{name:"Nora Vale",schedule:[[1122,1260,"Gazette"],[1260,1320,"Maggie's Diner"],[1320,1440,"Gazette"]]},
voss:{name:"Dr. Elena Voss",schedule:[[1122,1440,"Clinic"]]},
anna:{name:"Anna Malric",type:"apparition",schedule:[]}},
events:[
{id:"mercer_call",at:1122,windowEnd:1160,location:"St. Bartholomew's",summary:"Mercer calls Malric about Emily Vance."},
{id:"anna_voice",at:1122,windowEnd:1180,location:"St. Bartholomew's",summary:"A voice resembling Anna calls from elsewhere in the church."},
{id:"mercer_vance",at:1150,location:"Vance Residence",summary:"Mercer begins interviewing David and Caleb."},
{id:"nora_redwater",at:1215,location:"Gazette",summary:"Nora finds Samuel's Redwater reference."},
{id:"gabriel_archive",at:1260,location:"St. Bartholomew's",summary:"Gabriel checks the water-damaged archive material."},
{id:"clinic_cases",at:1290,location:"Clinic",summary:"Unusual headache/tinnitus cases increase."},
{id:"anna_second",at:1350,location:"St. Bartholome's",summary:"Anna may manifest again if Malric ignored the first contact."},
{id:"blackridge_power",at:1395,location:null,summary:"Blackridge begins powering the receiver."},
{id:"dream_onset",at:1432,location:null,summary:"Unusually vivid dreams begin across Whispering Falls."}
],
rules:{knowledge:"World truth is not character knowledge.",agency:"Never author Malric's dialogue, beliefs, motives or decisions.",narration:"Player-facing story only; no engine language.",time:"NPC schedules and events advance whenever Malric spends time.",sliceEnd:"At midnight Day -1 transitions toward Day 0; 2:17 AM belongs to the next slice."}};
