;(async()=>{const fs=require("fs"),assert=require("assert"),vm=require("vm");let ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync("engine.js","utf8"),ctx);const E=ctx.window.Engine03;
let source=fs.readFileSync("api/resolve.js","utf8").replace(/^import .*semantic\.js";\n/,"").replace("export default async function handler","async function handler").replace("let semantic=null;try{semantic=await interpret(raw,s,b.preflight||{})}catch(e){semantic=null}o.semantic=semantic;","let semantic=null;o.semantic=null;")+"\nmodule.exports=handler;";let box={module:{exports:{}},exports:{}};vm.runInNewContext(source,box);const resolve=box.module.exports;
function state(){return{loc:"St. Bartholomew's",knowledge:E.initialKnowledge(),scene:{mode:"FREE_ACTION",npc:null,subject:"opening choice"},opening:{mercerCall:true,annaVoice:true,annaEncountered:false},npcs:{gabriel:{loc:"St. Bartholomew's"},mercer:{loc:"Sheriff's Office"},anna:{present:false,loc:null}},conversation:{anna:{turns:0,accused:false,askedDeath:false}}}}
async function call(s,action){let result,status;await resolve({method:"POST",body:{action,state:s}},{status(n){status=n;return this},json(x){result=x;return x}});assert.equal(status,200);return E.invariant(result)}
function apply(s,o){if(o.locationDiscovered)E.discover(s.knowledge,o.locationDiscovered);if(o.routeDiscovered){let p=o.routeDiscovered.split(" → ");if(p.length===2)E.discoverRoute(s.knowledge,p[0],p[1])}if(o.location)s.loc=o.location;if(o.scene)s.scene=o.scene;if(o.statePatch&&o.statePatch.openingChoice==="mercer"){s.opening.mercerCall=false}s.opening.annaVoice=s.opening.annaVoice!==false;return s}
let tests=[];async function t(n,f){try{await f();console.log("PASS",n);tests.push(true)}catch(e){console.log("FAIL",n,"—",e.message);tests.push(false)}}
await t("Mercer branch stays upstairs",async()=>{let s=state(),o=await call(s,"agree to favor");assert.equal(o.location,"Rectory");assert(!/basement/i.test(o.narration));assert.equal(o.scene.npc,"mercer")});
await t("Mercer pending offer accepts and clears",async()=>{let s=state();s.loc="Rectory";s.scene={mode:"CONVERSATION",npc:"mercer",subject:"Emily Vance",pendingOffer:{id:"help_emily",from:"mercer"}};s.opening.mercerCall=false;s.opening.annaVoice=false;let o=await call(s,"I agree to go with you");assert(/Vance address|meet him at the house/i.test(o.narration));assert.equal(o.scene.mode,"FREE_ACTION");assert(!o.scene.pendingOffer);assert.equal(o.statePatch.mercerAccepted,true)});
await t("Mercer pending offer refusal clears",async()=>{let s=state();s.loc="Rectory";s.scene={mode:"CONVERSATION",npc:"mercer",subject:"Emily Vance",pendingOffer:{id:"help_emily",from:"mercer"}};s.opening.mercerCall=false;s.opening.annaVoice=false;let o=await call(s,"No, not now");assert(/refusal|heading to the Vance/i.test(o.narration));assert.equal(o.scene.mode,"FREE_ACTION");assert.equal(o.statePatch.mercerDeclined,true)});
await t("Follow voice discovers threshold, not basement arrival",async()=>{let s=state(),o=await call(s,"follow the voice");assert.equal(o.location,"St. Bartholomew's");assert.equal(o.locationDiscovered,"Church Basement");assert(/stair|door/i.test(o.narration));assert(!/at the far end stands/i.test(o.narration))});
await t("Discovered threshold continues one physical step",async()=>{let s=state();s.knowledge.locations["Church Basement"]="DISCOVERED";s.opening.annaVoice=false;s.scene={mode:"FREE_ACTION",npc:null,subject:"voice below"};let o=await call(s,"open the door and follow the voice");assert.equal(o.location,"Church Basement");assert.equal(o.statePatch.annaEncountered,true);assert(/stairs|lower level/i.test(o.narration))});
await t("Anna can be addressed after manifestation appears",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.opening.annaEncountered=true;s.opening.annaVoice=false;s.npcs.anna={present:true,loc:"Church Basement"};s.scene={mode:"FREE_ACTION",npc:"anna",subject:"first apparition"};let o=await call(s,"talk to Anna");assert.equal(o.scene.mode,"CONVERSATION");assert.equal(o.scene.npc,"anna");assert(!/no one here/i.test(o.narration))});
await t("Unknown Sublevel 4 is not revealed",async()=>{let s=state(),o=await call(s,"go to Blackridge Sublevel 4");assert(!/sublevel 4|blackridge/i.test(o.narration.toLowerCase()));assert.equal(o.location,"St. Bartholomew's")});
await t("No developer diagnostics leak",async()=>{let s=state(),o=await call(s,"do something strange");assert(!/resolver|context|state|available action|established context/i.test(o.narration))});
await t("Talk to Anna cannot teleport before encounter",async()=>{let s=state(),o=await call(s,"talk to Anna");assert.notEqual(o.location,"Church Basement")});
await t("Anna conversation persists once present",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=await call(s,"how did you die?");assert.equal(o.scene.mode,"CONVERSATION");assert.equal(o.scene.npc,"anna");assert(/road|rain|guardrail/i.test(o.narration))});
await t("Bare question stays in Anna conversation",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.npcs.anna={present:true,loc:"Church Basement"};let o=await call(s,"Where are you?");assert.equal(o.scene.npc,"anna");assert(/Here, with you|avoided naming/i.test(o.narration));assert(/Asked Anna/i.test(o.journal))});
await t("Embrace Anna produces physical evidence",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.npcs.anna={present:true,loc:"Church Basement"};let o=await call(s,"Embrace Anna");assert.equal(o.scene.npc,"anna");assert(/cold|weight|contact/i.test(o.narration));assert(o.evidenceAdded&&o.evidenceAdded.length)});
await t("Unknown Anna dialogue does not use old stock loop",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna",subject:"identity"};s.opening.annaEncountered=true;s.npcs.anna={present:true,loc:"Church Basement"};let o=await call(s,"Tell me something only Anna would know");assert(!/Ask me what you actually want to know/i.test(o.narration));assert.equal(o.scene.npc,"anna")});
await t("Leaving Anna ends conversation",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=await call(s,"go upstairs");assert.equal(o.location,"Rectory");assert.notEqual(o.scene.mode,"CONVERSATION")});
await t("Physical action during conversation is not treated as speech",async()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=await call(s,"touch her");assert(/fingers|sleeve|fabric/i.test(o.narration))});
await t("Force action creates roll pending",async()=>{let s=state();s.opening.mercerCall=false;s.opening.annaVoice=false;let o=await call(s,"force open the locked door");assert(o.rollRequired);assert.equal(o.scene.mode,"ROLL_PENDING")});
await t("Look around returns perceivable scene content",async()=>{let s=state();let o=await call(s,"look around");assert(/church|surroundings|immediate/i.test(o.narration));assert(!/nothing immediately changes/i.test(o.narration));assert(/Surveyed/i.test(o.journal))});
await t("Look around cannot invent secret locations",async()=>{let s=state(),o=await call(s,"look around");assert(!/archive|basement|sublevel|old whisper/i.test(o.narration.toLowerCase()))});
let passed=tests.filter(Boolean).length;console.log("SCENARIOS",passed+"/"+tests.length);if(passed!==tests.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});