const fs=require("fs"),assert=require("assert"),vm=require("vm");let ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync("engine.js","utf8"),ctx);const E=ctx.window.Engine03;
let source=fs.readFileSync("api/resolve.js","utf8").replace("export default function handler","function handler")+"\nmodule.exports=handler;";let box={module:{exports:{}},exports:{}};vm.runInNewContext(source,box);const resolve=box.module.exports;
function state(){return{loc:"St. Bartholomew's",knowledge:E.initialKnowledge(),scene:{mode:"FREE_ACTION",npc:null,subject:"opening choice"},opening:{mercerCall:true,annaVoice:true,annaEncountered:false},npcs:{gabriel:{loc:"St. Bartholomew's"},mercer:{loc:"Sheriff's Office"},anna:{present:false,loc:null}},conversation:{anna:{turns:0,accused:false,askedDeath:false}}}}
function call(s,action){let result,status;resolve({method:"POST",body:{action,state:s}},{status(n){status=n;return this},json(x){result=x;return x}});assert.equal(status,200);return E.invariant(result)}
function apply(s,o){if(o.locationDiscovered)E.discover(s.knowledge,o.locationDiscovered);if(o.routeDiscovered){let p=o.routeDiscovered.split(" → ");if(p.length===2)E.discoverRoute(s.knowledge,p[0],p[1])}if(o.location)s.loc=o.location;if(o.scene)s.scene=o.scene;if(o.statePatch&&o.statePatch.openingChoice==="mercer"){s.opening.mercerCall=false}s.opening.annaVoice=s.opening.annaVoice!==false;return s}
let tests=[];function t(n,f){try{f();console.log("PASS",n);tests.push(true)}catch(e){console.log("FAIL",n,"—",e.message);tests.push(false)}}
t("Mercer branch stays upstairs",()=>{let s=state(),o=call(s,"agree to favor");assert.equal(o.location,"Rectory");assert(!/basement/i.test(o.narration));assert.equal(o.scene.npc,"mercer")});
t("Follow voice discovers threshold, not basement arrival",()=>{let s=state(),o=call(s,"follow the voice");assert.equal(o.location,"St. Bartholomew's");assert.equal(o.locationDiscovered,"Church Basement");assert(/stair|door/i.test(o.narration));assert(!/at the far end stands/i.test(o.narration))});
t("Unknown Sublevel 4 is not revealed",()=>{let s=state(),o=call(s,"go to Blackridge Sublevel 4");assert(!/sublevel 4|blackridge/i.test(o.narration.toLowerCase()));assert.equal(o.location,"St. Bartholomew's")});
t("No developer diagnostics leak",()=>{let s=state(),o=call(s,"do something strange");assert(!/resolver|context|state|available action|established context/i.test(o.narration))});
t("Talk to Anna cannot teleport before encounter",()=>{let s=state(),o=call(s,"talk to Anna");assert.notEqual(o.location,"Church Basement")});
t("Anna conversation persists once present",()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=call(s,"how did you die?");assert.equal(o.scene.mode,"CONVERSATION");assert.equal(o.scene.npc,"anna");assert(/road|rain|guardrail/i.test(o.narration))});
t("Leaving Anna ends conversation",()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=call(s,"go upstairs");assert.equal(o.location,"Rectory");assert.notEqual(o.scene.mode,"CONVERSATION")});
t("Physical action during conversation is not treated as speech",()=>{let s=state();s.loc="Church Basement";s.knowledge.locations["Church Basement"]="DISCOVERED";s.scene={mode:"CONVERSATION",npc:"anna"};s.opening.annaEncountered=true;s.opening.annaVoice=false;let o=call(s,"touch her");assert(/fingers|sleeve|fabric/i.test(o.narration))});
t("Force action creates roll pending",()=>{let s=state();s.opening.mercerCall=false;s.opening.annaVoice=false;let o=call(s,"force open the locked door");assert(o.rollRequired);assert.equal(o.scene.mode,"ROLL_PENDING")});
t("Look around cannot invent secret locations",()=>{let s=state(),o=call(s,"look around");assert(!/archive|basement|sublevel|old whisper/i.test(o.narration.toLowerCase()))});
let passed=tests.filter(Boolean).length;console.log("SCENARIOS",passed+"/"+tests.length);if(passed!==tests.length)process.exitCode=1;